import os, spacy

from bot import Bottimus

filename = "archive.sav"
if os.path.isfile(filename):
    Prime = Bottimus.load(filename)
else:
    Prime = Bottimus(
        generator_text=[],
        responder_text=[
            "Who are you?",
            "I am a bot.",
            "Why are you here?",
            "To entertain you.",
        ],
        command_text=["What's your favorite director?", "Definitely #director#"],
        grammar={
            "director": "#d_first# #d_last#",
            "d_first": [
                "Adrian",
                "Akira",
                "Alejandro",
                "Alfonso",
                "Ang",
                "Angelina",
                "Antoine",
                "Ava",
                "Barry",
                "Ben",
                "Bernardo",
                "Bong",
                "Brad",
                "Brian",
                "Byron",
                "Buster",
                "Charlie",
                "Chuck",
                "Clint",
                "D. W.",
                "Damien",
                "Danny",
                "Darren",
                "David",
                "Doug",
                "Duncan",
                "Elia",
                "Ethan",
                "F. Gary",
                "Francis Ford",
                "Frank",
                "Garry",
                "Gene",
                "George",
                "George Roy",
                "Gil",
                "Guillermo",
                "Hugh",
                "J. J.",
                "Jack",
                "Jackie",
                "James",
                "Jane",
                "Jean-Luc",
                "Jennifer",
                "Jim",
                "Jodie",
                "Joe",
                "Joel",
                "John",
                "Jon",
                "Kathryn",
                "Ken",
                "Kenneth",
                "Kevin",
                "Lewis",
                "Louis",
                "Luc",
                "Mark L.",
                "Martin",
                "Masaki",
                "Mel",
                "Michael",
                "Neil",
                "Neill",
                "P. T.",
                "Patty",
                "Paul",
                "Peter",
                "Philip",
                "Rian",
                "Richard",
                "Robert",
                "Roland",
                "Ron",
                "Sergio",
                "Shawn",
                "Sidney",
                "Sofia",
                "Spike",
                "Stanley",
                "Terrence",
                "Terry",
                "Tim",
                "Walt",
                "Walter",
                "Warren",
                "Werner",
                "Wes",
                "William",
                "Woody",
            ],
            "d_last": [
                "Abrams",
                "Affleck",
                "Allen",
                "Altman",
                "Anderson",
                "Aronofsky",
                "Attenborough",
                "Bay",
                "Beatty",
                "Bertolucci",
                "Besson",
                "Bigelow",
                "Bird",
                "Blomkamp",
                "Bogdanovich" "Boyle",
                "Branagh",
                "Brooks",
                "Burns",
                "Burton",
                "Cameron",
                "Campbell",
                "Campion",
                "Capra",
                "Carpenter",
                "Chan",
                "Chaplin",
                "Chazelle",
                "Clayton",
                "Clooney",
                "Coen",
                "Coppola",
                "Costner",
                "Craven",
                "Crichton",
                "Cronenberg",
                "Cuarón",
                "Curtis",
                "del Toro",
                "De Palma",
                "DeVito",
                "Disney",
                "Donner",
                "DuVernay",
                "Eastwood",
                "Emmerich",
                "Favreau",
                "Feig",
                "Fincher",
                "Foley",
                "Ford",
                "Foster",
                "Friedkin",
                "Fuqua",
                "G. Iñárritu",
                "Gibson",
                "Gilbert",
                "Gilliam",
                "Godard",
                "Gray",
                "Greengrass",
                "Gunn",
                "Henson",
                "Herzog",
                "Hill",
                "Howard",
                "Hudson",
                "Hughes",
                "Jackson",
                "Jenkins",
                "Jodorowsky",
                "Johnson",
                "Johnston",
                "Johns",
                "Jolie",
                "Jonze",
                "Joon-ho",
                "Kaufman",
                "Kazan",
                "Keaton",
                "Kelly",
                "Kenan",
                "Kobayashi",
                "Kramer",
                "Kubrick",
                "Kurosawa",
                "Lee",
                "Leone",
                "Le Prince",
                "Lester",
                "Levinson",
                "Levy",
                "Liman",
                "Lloyd",
                "Lucas",
                "Lumet",
                "Lynch",
                "Lyne",
                "Macdonald",
                "Malick",
                "Malle",
                "Mangold",
                "Mann",
                "Marquand",
                "Marshall",
                "McDonagh",
                "McGuigan",
                "McNaughton",
                "McTiernan",
            ],
        },
    )
    # Prime.save("model.pkl")
print(Prime.make_sentence())
print(Prime.make_sentence("Whats ur fav director"))
